baseURL = 'https://git-workshop.zhukovsd.it/'
languageCode = 'ru'
title = 'IT Ментор | Git Workshop'
theme = 'hugo-book'
enableGitInfo = true

[params]
  BookTheme = 'auto'
  BookSection = '*'
  BookPortableLinks = true
  BookRepo = 'https://git-workshop.zhukovsd.it'
  BookCommitPath = 'commit'
  BookEditPath = 'edit/main'
