baseURL = 'https://zhukovsd.github.io/git-workshop/'
languageCode = 'ru'
title = 'Git Workshop'
theme = 'hugo-book'
enableGitInfo = true

[params]
  BookTheme = 'auto'
  BookSection = '*'
  BookPortableLinks = true
  BookRepo = 'https://github.com/zhukovsd/git-workshop'
  BookCommitPath = 'commit'
  BookEditPath = 'edit/main'

[menu]
  [[menu.after]]
    name = 'Блог'
    url = 'https://zhukovsd.it/posts/'
    weight = 1
    pre = '<strong>'
    post = '</strong>'
    params = { class = 'menu-bold-link' }

  [[menu.after]]
    name = 'Роадмапы'
    identifier = 'roadmaps'
    weight = 10
    pre = '<strong>'
    post = '</strong>'
    params = { class = 'menu-section-heading' }

  [[menu.after]]
    name = 'Java роадмап'
    url = 'https://zhukovsd.github.io/java-backend-learning-course/'
    parent = 'roadmaps'
    weight = 10

  [[menu.after]]
    name = 'Python роадмап'
    url = 'https://zhukovsd.github.io/python-backend-learning-course/'
    parent = 'roadmaps'
    weight = 20

  [[menu.after]]
    name = 'Golang роадмап'
    url = 'https://zhukovsd.github.io/golang-backend-learning-course/'
    parent = 'roadmaps'
    weight = 30

  [[menu.after]]
    name = 'Методички'
    identifier = 'handbooks'
    weight = 20
    pre = '<strong>'
    post = '</strong>'
    params = { class = 'menu-section-heading' }

  [[menu.after]]
    name = 'Java методичка'
    url = 'https://zhukovsd.github.io/java-backend-interview-prep/'
    parent = 'handbooks'
    weight = 10

  [[menu.after]]
    name = 'Python методичка'
    url = 'https://zhukovsd.github.io/python-backend-interview-prep/'
    parent = 'handbooks'
    weight = 20

  [[menu.after]]
    name = 'Видео'
    identifier = 'videos'
    weight = 30
    pre = '<strong>'
    post = '</strong>'
    params = { class = 'menu-section-heading' }

  [[menu.after]]
    name = 'YouTube'
    url = 'https://www.youtube.com/@zhukovsd_it_mentor'
    parent = 'videos'
    weight = 10

  [[menu.after]]
    name = 'VK Видео'
    url = 'https://vkvideo.ru/@zhukovsd_it_mentor'
    parent = 'videos'
    weight = 20

  [[menu.after]]
    name = 'Сообщество'
    identifier = 'community'
    weight = 40
    pre = '<strong>'
    post = '</strong>'
    params = { class = 'menu-section-heading' }

  [[menu.after]]
    name = 'Telegram'
    url = 'https://t.me/zhukovsd_it_mentor'
    parent = 'community'
    weight = 10

  [[menu.after]]
    name = 'ВКонтакте'
    url = 'https://vk.ru/zhukovsd_it_mentor'
    parent = 'community'
    weight = 20
